import type { Asset } from "contentful";
import Head from "next/head";
import { useState, useEffect } from "react";
import { getAssets } from "../../contentful";
import AudioPlayer from "../components/audioplayer";

export async function getStaticProps() {
  const assets = await getAssets();
  const items = assets.items;
  return {
    props: {
      items,
    },
  };
}

interface Props {
  items: Asset[];
  isDarkMode: boolean;
  setDarkMode: React.Dispatch<React.SetStateAction<boolean>>;
}

export default function Soundboard({ items, isDarkMode, setDarkMode }: Props) {
  const [volume, setVolume] = useState(0.5);

  useEffect(() => {
    if (window.matchMedia("(prefers-color-scheme: light)").matches) {
      setDarkMode(false);
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])
  
  console.log(isDarkMode)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Soundboard</h1>
        <h2>Volume:</h2>
        <input
          type="range"
          min={0}
          max={1}
          step={0.01}
          value={volume}
          onChange={(e) => setVolume(Number(e.target.value))}
        />
        <button onClick={() => setDarkMode(prev => !prev)}>Swap to dark mode?</button>
        <ul>
          {items.map((item) => (
            <li key={item.sys.id}>
              <AudioPlayer src={item.fields.file.url} title={item.fields.title} volume={volume} />
            </li>
          ))}
        </ul>
      </main>
    </>
  );
}
